// eslint-disable-next-line filenames/match-exported
import "@szhsin/react-menu/dist/index.css";
import "@szhsin/react-menu/dist/transitions/slide.css";
import type { Metadata } from "next";
import { M_PLUS_1 as MPlus1 } from "next/font/google";
import "ress";
import "./globals.scss";
import "./mq-settings.scss";
import Layout from "@/components/Layout";

const mPlus1 = MPlus1({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html data-color-mode="light" lang="ja">
      <body className={mPlus1.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
