// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

declare namespace Contentful {
  export interface IBlogFields {
    /** Title */
    title: LocalizedField<string>;

    /** Talent Id */
    talentId: LocalizedField<string>;

    /** Content */
    content: LocalizedField<Document>;
  }

  export interface IBlog extends Entry<IBlogFields> {
    sys: {
      id: string;
      type: string;
      createdAt: string;
      updatedAt: string;
      locale: string;
      contentType: {
        sys: {
          id: "blog";
          linkType: "ContentType";
          type: "Link";
        };
      };
    };
  }

  export type CONTENT_TYPE = "blog";

  export type IEntry = IBlog;

  export type LOCALE_CODE = "ja";

  export type CONTENTFUL_DEFAULT_LOCALE_CODE = "ja";

  export type LocalizedField<T> = Partial<Record<LOCALE_CODE, T>>;

  // We have to use our own localized version of Asset because of a bug in contentful https://github.com/contentful/contentful.js/issues/208
  export interface Asset {
    sys: Sys;
    fields: {
      title: LocalizedField<string>;
      description: LocalizedField<string>;
      file: LocalizedField<{
        url: string;
        details: {
          size: number;
          image?: {
            width: number;
            height: number;
          };
        };
        fileName: string;
        contentType: string;
      }>;
    };
    toPlainObject(): object;
  }
}

export as namespace Contentful;
export = Contentful;
